name: Set Up Python Environment

on: [push]

jobs:
  setup-python:
    runs-on: ubuntu-latest
    environment: Development
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TEST_KEY: ${{ secrets.TEST_API_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python src/main.py
