name: Set Up Python Environment

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TEST_KEY: ${{ secrets.TEST_API_KEY }}

jobs:
  setup-python:
    runs-on: ubuntu-latest
    environment: Development
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TEST_KEY: ${{ secrets.TEST_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          python src/main.py
